import { useCallback, useEffect, useMemo, useState } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { normalizeAppLanguage, useAppTheme } from "../context/ThemeContext";

const LANGUAGE_STORAGE_KEY = "app_language";

const LANGUAGE_OPTION_LABELS = {
  English: {
    English: "English",
    Nepali: "Nepali",
  },
  Nepali: {
    English: "अंग्रेजी",
    Nepali: "नेपाली",
  },
};

const ROLE_LABELS = {
  admin: {
    English: "Admin",
    Nepali: "प्रशासक",
  },
  counsellor: {
    English: "Counsellor",
    Nepali: "परामर्शदाता",
  },
  therapist: {
    English: "Therapist",
    Nepali: "थेरापिस्ट",
  },
  police: {
    English: "Police",
    Nepali: "प्रहरी",
  },
  municipality: {
    English: "Municipality",
    Nepali: "नगरपालिका",
  },
  user: {
    English: "User",
    Nepali: "प्रयोगकर्ता",
  },
};

const EXACT_TRANSLATIONS = {
  "Share your need": "आफ्नो आवश्यकता साझा गर्नुहोस्",
  "Ask for support": "सहयोग माग्नुहोस्",
  "Tell people what you need and how they can help.": "तपाईंलाई के चाहिएको छ र अरूले कसरी मद्दत गर्न सक्छन् भन्ने कुरा साझा गर्नुहोस्।",
  "Your requests are not available right now. Please try again soon.": "तपाईंका अनुरोधहरू अहिले उपलब्ध छैनन्। कृपया केही बेरपछि फेरि प्रयास गर्नुहोस्।",
  "Loading help requests...": "सहयोग सम्बन्धी अनुरोधहरू लोड हुँदैछन्...",
  "No verified requests yet": "अहिलेसम्म प्रमाणित अनुरोध छैनन्",
  "Verified requests will appear here when they are ready to receive support.": "सहयोग लिन तयार भएका प्रमाणित अनुरोधहरू यहाँ देखिनेछन्।",
  "If you need help, you can send a request here anytime.": "यदि तपाईंलाई सहयोग चाहिन्छ भने, यहाँ जुनसुकै बेला अनुरोध पठाउन सक्नुहुन्छ।",
  "Support Request": "सहयोग अनुरोध",
  "Location will appear here": "स्थान यहाँ देखिनेछ",
  "More details will appear here.": "थप विवरण यहाँ देखिनेछ।",
  "Verification note": "प्रमाणिकरण टिप्पणी",
  "Payment QR will appear here when it is available.": "भुक्तानीको QR उपलब्ध भएपछि यहाँ देखिनेछ।",
  "Contact & in-person help": "सम्पर्क र प्रत्यक्ष सहयोग",
  "How you can help in person": "तपाईंले प्रत्यक्ष रूपमा कसरी मद्दत गर्न सक्नुहुन्छ",
  "Support people with clear, careful follow-up.": "स्पष्ट र जिम्मेवार फलो-अपमार्फत मानिसहरूलाई सहयोग गर्नुहोस्।",
  "Review requests, keep support updates organized, and close requests when help is complete.": "अनुरोधहरू समीक्षा गर्नुहोस्, सहयोग सम्बन्धी अपडेटहरू मिलाएर राख्नुहोस्, र मद्दत पूरा भएपछि अनुरोध बन्द गर्नुहोस्।",
  "Update received support": "प्राप्त सहयोग अपडेट गर्नुहोस्",
  "Review note:": "समीक्षा टिप्पणी:",
  "If you need help, you can ask here. If you are able to give, you can help someone in need too.": "यदि तपाईंलाई सहयोग चाहिन्छ भने यहाँ अनुरोध गर्न सक्नुहुन्छ। यदि तपाईं सहयोग गर्न सक्नुहुन्छ भने, आवश्यकतामा रहेको अरू कसैलाई पनि मद्दत गर्न सक्नुहुन्छ।",
  "Share your request with care, or support an approved appeal and make life a little easier for someone today.": "आफ्नो अनुरोध आदरका साथ साझा गर्नुहोस्, वा स्वीकृत अपिललाई सहयोग गरेर आज कसैको जीवन अलि सजिलो बनाउनुहोस्।",
  English: "अंग्रेजी",
  Nepali: "नेपाली",
  Back: "फिर्ता",
  Cancel: "रद्द गर्नुहोस्",
  "Add Image": "तस्बिर थप्नुहोस्",
  "Add Audio": "अडियो थप्नुहोस्",
  "Add Video": "भिडियो थप्नुहोस्",
  "Choose how to add audio for this report.": "यो रिपोर्टका लागि अडियो कसरी थप्ने भनेर छान्नुहोस्।",
  "Choose how to add an image for this report.": "यो रिपोर्टका लागि तस्बिर कसरी थप्ने भनेर छान्नुहोस्।",
  "Choose how to add a video for this report.": "यो रिपोर्टका लागि भिडियो कसरी थप्ने भनेर छान्नुहोस्।",
  Upload: "अपलोड गर्नुहोस्",
  Capture: "खिच्नुहोस्",
  Record: "रेकर्ड गर्नुहोस्",
  "Stop Recording": "रेकर्ड रोक्नुहोस्",
  Recording: "रेकर्डिङ",
  "Recording:": "रेकर्डिङ: ",
  "Recording now": "रेकर्ड हुँदैछ",
  "Tap audio again to finish recording.": "रेकर्ड समाप्त गर्न अडियो फेरि थिच्नुहोस्।",
  "Preparing audio...": "अडियो तयार हुँदैछ...",
  Continue: "अगाडि बढ्नुहोस्",
  Close: "बन्द गर्नुहोस्",
  OK: "ठीक छ",
  Submit: "पेश गर्नुहोस्",
  Save: "सुरक्षित गर्नुहोस्",
  "Save Profile": "प्रोफाइल सुरक्षित गर्नुहोस्",
  "Saving...": "सुरक्षित हुँदै...",
  "Updating...": "अपडेट हुँदै...",
  Reload: "पुन: लोड गर्नुहोस्",
  Refresh: "रिफ्रेस गर्नुहोस्",
  "Refreshing...": "रिफ्रेस हुँदै...",
  Search: "खोज्नुहोस्",
  Settings: "सेटिङ",
  Profile: "प्रोफाइल",
  Home: "होम",
  Chat: "च्याट",
  SOS: "एसओएस",
  Support: "सहायता",
  Donate: "दान",
  Reporting: "रिपोर्टिङ",
  Traffic: "ट्राफिक",
  Counseling: "परामर्श",
  Therapy: "थेरापी",
  Counsellor: "परामर्शदाता",
  Therapist: "थेरापिस्ट",
  Police: "प्रहरी",
  Municipality: "नगरपालिका",
  User: "प्रयोगकर्ता",
  Admin: "प्रशासक",
  Users: "प्रयोगकर्ताहरू",
  Staff: "कर्मचारी",
  Reports: "रिपोर्टहरू",
  Donations: "दानहरू",
  Overview: "सारांश",
  Account: "खाता",
  Session: "सेसन",
  Sessions: "सेसनहरू",
  Appointments: "अपोइन्टमेन्टहरू",
  Clients: "सेवाग्राहीहरू",
  Contact: "सम्पर्क",
  Emergency: "आपतकालीन",
  "Request ID": "अनुरोध आईडी",
  Date: "मिति",
  Status: "स्थिति",
  Urgent: "तत्काल",
  Help: "सहयोग",
  Care: "हेरचाह",
  Wellbeing: "कल्याण",
  Safety: "सुरक्षा",
  Community: "समुदाय",
  Road: "सडक",
  "Fast Paths": "छिटो पहुँच",
  "Core services": "मुख्य सेवाहरू",
  "Private Help": "गोप्य सहयोग",
  Safe: "सुरक्षित",
  "SOS support": "एसओएस सहायता",
  "Counseling & therapy": "परामर्श र थेरापी",
  "Priority Actions": "प्राथमिक कार्यहरू",
  "Quick Access": "द्रुत पहुँच",
  "View helplines": "हेल्पलाइन हेर्नुहोस्",
  "Staff access": "कर्मचारी पहुँच",
  "Help Chat": "सहायता च्याट",
  "Simple AI assistant": "सरल एआई सहायक",
  "Ask for help...": "सहायता माग्नुहोस्...",
  "Type a message...": "सन्देश टाइप गर्नुहोस्...",
  "Type your message": "आफ्नो सन्देश टाइप गर्नुहोस्",
  "My booked sessions": "मेरो बुक गरिएका सेसनहरू",
  "View Booked Sessions": "बुक गरिएका सेसनहरू हेर्नुहोस्",
  "Continue to Counsellors": "परामर्शदातातर्फ अगाडि बढ्नुहोस्",
  "Continue to Therapist Booking": "थेरापिस्ट बुकिङतर्फ अगाडि बढ्नुहोस्",
  "Continue to Booking": "बुकिङतर्फ अगाडि बढ्नुहोस्",
  "Continue to Chat": "च्याटतर्फ अगाडि बढ्नुहोस्",
  "Session details": "सेसन विवरण",
  "Therapy request": "थेरापी अनुरोध",
  "Counseling Intake": "परामर्श प्रारम्भ",
  "Therapy Intake": "थेरापी प्रारम्भ",
  "Start with a clear request, then move into booking.": "स्पष्ट अनुरोधबाट सुरु गर्नुहोस्, त्यसपछि बुकिङतर्फ जानुहोस्।",
  "Move from request to therapy booking in one calmer flow.": "एकै शान्त प्रक्रियामा अनुरोधबाट थेरापी बुकिङसम्म जानुहोस्।",
  "Smaller inputs, better grouping, and a calmer path to getting help.": "साना इनपुट, राम्रो समूहबद्धता, र सहायता पाउने शान्त बाटो।",
  "The screen now keeps booked sessions visible without burying the form.": "यो स्क्रिनले फारम लुकाइने बिना बुक गरिएका सेसनहरू देखाइराख्छ।",
  "Problem / Issue": "समस्या / विषय",
  Age: "उमेर",
  Gender: "लिङ्ग",
  "Language Preference": "भाषा प्राथमिकता",
  "Mode of Communication": "सम्पर्कको माध्यम",
  Description: "विवरण",
  "Choose one": "एउटा छान्नुहोस्",
  Select: "छान्नुहोस्",
  "Choose language": "भाषा छान्नुहोस्",
  "Choose mode": "माध्यम छान्नुहोस्",
  "Share any context that will help the counsellor prepare.": "परामर्शदातालाई तयारी गर्न मद्दत गर्ने सन्दर्भ साझा गर्नुहोस्।",
  "Share any context that will help the therapist prepare.": "थेरापिस्टलाई तयारी गर्न मद्दत गर्ने सन्दर्भ साझा गर्नुहोस्।",
  Male: "पुरुष",
  Female: "महिला",
  Anxiety: "चिन्ता",
  Depression: "अवसाद",
  "Family Issues": "पारिवारिक समस्या",
  "Relationship Issues": "सम्बन्ध समस्या",
  Other: "अन्य",
  Online: "अनलाइन",
  Offline: "अफलाइन",
  Pending: "पेन्डिङ",
  pending: "पेन्डिङ",
  Approved: "स्वीकृत",
  approved: "स्वीकृत",
  Confirmed: "पुष्टि भएको",
  confirmed: "पुष्टि भएको",
  Completed: "सम्पन्न",
  completed: "सम्पन्न",
  Cancelled: "रद्द गरिएको",
  cancelled: "रद्द गरिएको",
  "Mark Completed": "सम्पन्न चिन्ह लगाउनुहोस्",
  Confirm: "पुष्टि गर्नुहोस्",
  Complete: "सम्पन्न गर्नुहोस्",
  Decline: "अस्वीकार गर्नुहोस्",
  "Latest Session": "नवीनतम सेसन",
  Concern: "समस्या",
  Format: "ढाँचा",
  "Chat Ready": "च्याट तयार",
  Reviewable: "समीक्षा योग्य",
  "Ratings & Reviews": "मूल्याङ्कन र समीक्षा",
  "Personal Details": "व्यक्तिगत विवरण",
  "Full Name": "पूरा नाम",
  Phone: "फोन",
  "Working Area": "कार्य क्षेत्र",
  Qualification: "योग्यता",
  Bio: "परिचय",
  Email: "इमेल",
  Password: "पासवर्ड",
  "New Email": "नयाँ इमेल",
  "Current Password": "हालको पासवर्ड",
  "New Password": "नयाँ पासवर्ड",
  "Confirm New Password": "नयाँ पासवर्ड पुष्टि गर्नुहोस्",
  "Update Email": "इमेल अपडेट गर्नुहोस्",
  "Update Password": "पासवर्ड अपडेट गर्नुहोस्",
  "Use your password to confirm email changes.": "इमेल परिवर्तन पुष्टि गर्न आफ्नो पासवर्ड प्रयोग गर्नुहोस्।",
  "Choose a secure password with at least 6 characters.": "कम्तीमा ६ अक्षर भएको सुरक्षित पासवर्ड छान्नुहोस्।",
  Missing: "अपूर्ण",
  Error: "त्रुटि",
  Failed: "असफल",
  "Submit failed": "पेश गर्न असफल",
  "Booking failed": "बुकिङ असफल",
  "Send failed": "पठाउन असफल",
  "Call failed": "कल गर्न असफल",
  "Create failed": "सिर्जना गर्न असफल",
  Created: "सिर्जना गरियो",
  "Update failed": "अपडेट असफल",
  "Delete failed": "मेटाउन असफल",
  "Dashboard error": "ड्यासबोर्ड त्रुटि",
  "Users error": "प्रयोगकर्ता त्रुटि",
  "Reports error": "रिपोर्ट त्रुटि",
  "Staff error": "कर्मचारी त्रुटि",
  "Donations error": "दान त्रुटि",
  "Missing info": "जानकारी अपूर्ण",
  "Missing request": "अनुरोध भेटिएन",
  "Missing requestId": "अनुरोध आईडी भेटिएन",
  Incomplete: "अपूर्ण",
  "Invalid age": "अमान्य उमेर",
  Submitted: "पेश गरियो",
  "Form Submitted": "फारम पेश गरियो",
  Bookings: "बुकिङहरू",
  "Loading your bookings...": "तपाईंका बुकिङहरू लोड हुँदै...",
  "No bookings yet. Submit the form and book a therapist next.": "अहिलेसम्म कुनै बुकिङ छैन। पहिले फारम पेश गर्नुहोस् र त्यसपछि थेरापिस्ट बुक गर्नुहोस्।",
  "Please fill all required fields.": "कृपया सबै आवश्यक फिल्ड भर्नुहोस्।",
  "Please fill problem, age, gender, language and mode.": "कृपया समस्या, उमेर, लिङ्ग, भाषा र माध्यम भर्नुहोस्।",
  "Please enter a valid age.": "कृपया मान्य उमेर प्रविष्ट गर्नुहोस्।",
  "Your counseling request is ready. Choose a counsellor next.": "तपाईंको परामर्श अनुरोध तयार छ। अब परामर्शदाता छान्नुहोस्।",
  "Now pick a therapist and time slot.": "अब थेरापिस्ट र समय छनोट गर्नुहोस्।",
  "Please select a counsellor first.": "कृपया पहिले परामर्शदाता छान्नुहोस्।",
  "Please select a day and a time slot.": "कृपया दिन र समय छनोट गर्नुहोस्।",
  "Could not load counsellors": "परामर्शदाताहरू लोड गर्न सकिएन",
  "Could not load bookings": "बुकिङहरू लोड गर्न सकिएन",
  "Could not submit form": "फारम पेश गर्न सकिएन",
  "Failed to submit form": "फारम पेश गर्न असफल",
  "Failed to load your bookings": "तपाईंका बुकिङहरू लोड गर्न असफल",
  "No matching service found.": "मिल्दो सेवा भेटिएन।",
  "Try: counseling, traffic, support, payment": "जस्तै: परामर्श, ट्राफिक, सहायता, भुक्तानी",
  AngelTouch: "AngelTouch",
  "User Home": "प्रयोगकर्ता होम",
  "Help should feel immediate, calm, and obvious.": "सहयोग तुरुन्त, शान्त र स्पष्ट महसुस हुनुपर्छ।",
  "Search what you need, jump into reporting, or reach support in one clear flow.": "आवश्यक कुरा खोज्नुहोस्, रिपोर्टिङमा जानुहोस्, वा एकै स्पष्ट प्रक्रियामा सहायता पाउनुहोस्।",
  "Search reports, counseling, support, traffic...": "रिपोर्ट, परामर्श, सहायता, ट्राफिक खोज्नुहोस्...",
  "Care Hub": "हेरचाह केन्द्र",
  "Choose the kind of support that fits what you need right now.": "अहिले तपाईंलाई जे सहयोग उपयुक्त हुन्छ त्यही प्रकार छान्नुहोस्।",
  "Counseling, therapy, and NGO support now live in one cleaner flow with clearer choices.": "परामर्श, थेरापी र एनजिओ सहयोग अब अझ सफा र स्पष्ट विकल्पसहित एउटै प्रवाहमा छन्।",
  "Visit Counselors": "परामर्शदाताहरू हेर्नुहोस्",
  "Start with guided counseling support and booking.": "मार्गदर्शित परामर्श सहयोग र बुकिङबाट सुरु गर्नुहोस्।",
  "Urgent Therapy": "तत्काल थेरापी",
  "Move into therapy support when you need faster deeper care.": "छिटो र गहिरो हेरचाह चाहिँदा थेरापी सहयोगतर्फ जानुहोस्।",
  "Connect to NGOs": "एनजिओसँग जडान हुनुहोस्",
  "Reach support organizations and practical local help.": "सहयोगी संस्था र व्यवहारिक स्थानीय मद्दतसम्म पुग्नुहोस्।",
  "Start where you need help": "जहाँ सहायता चाहिन्छ त्यहीँबाट सुरु गर्नुहोस्",
  "Common user journeys": "सामान्य प्रयोगकर्ता यात्रा",
  "File crime, waste, or road reports with clearer next steps.": "अपराध, फोहोर वा सडकसम्बन्धी रिपोर्टहरू स्पष्ट अर्को चरणसहित दर्ता गर्नुहोस्।",
  "Find support, book a session, and continue chats in one place.": "सहायता खोज्नुहोस्, सेसन बुक गर्नुहोस्, र एकै ठाउँमा च्याट जारी राख्नुहोस्।",
  "Access traffic reporting, rules, and fine payment flows.": "ट्राफिक रिपोर्टिङ, नियम र जरिवाना भुक्तानी प्रक्रियामा पहुँच पाउनुहोस्।",
  "Connect to trusted NGOs and support organizations without digging through menus.": "मेनु खोजिरहनु नपरी विश्वसनीय एनजिओ र सहयोगी संस्थासँग जडान हुनुहोस्।",
  "Support verified requests and community needs with more trust.": "विश्वसनीय अनुरोध र सामुदायिक आवश्यकतालाई बढी भरोसासहित सहयोग गर्नुहोस्।",
  "Reach therapy support quickly for deeper ongoing care.": "दीर्घकालीन हेरचाहका लागि छिटो थेरापी सहायता पाउनुहोस्।",
  "Launch urgent calls and emergency actions instantly.": "तत्काल कल र आपतकालीन कार्य तुरुन्त सुरु गर्नुहोस्।",
  "Search client, concern, or status": "सेवाग्राही, समस्या वा स्थिति खोज्नुहोस्",
  "Search client, concern, mode, or date": "सेवाग्राही, समस्या, माध्यम वा मिति खोज्नुहोस्",
  "Search client, problem, mode, slot...": "सेवाग्राही, समस्या, माध्यम, समय खोज्नुहोस्...",
  "Search by name, email, ID...": "नाम, इमेल, आईडी अनुसार खोज्नुहोस्...",
  "Search by report code, type, area...": "रिपोर्ट कोड, प्रकार, क्षेत्र अनुसार खोज्नुहोस्...",
  "Search by requester, location, help type...": "अनुरोधकर्ता, स्थान, सहयोगको प्रकार अनुसार खोज्नुहोस्...",
  "Search type, area, status, priority...": "प्रकार, क्षेत्र, स्थिति, प्राथमिकता खोज्नुहोस्...",
  "Search type, area, status...": "प्रकार, क्षेत्र, स्थिति खोज्नुहोस्...",
  "Search by ID, area, status...": "आईडी, क्षेत्र, स्थिति अनुसार खोज्नुहोस्...",
  "e.g. TR-2026-000123": "जस्तै TR-2026-000123",
  "e.g. WM-2026-000123": "जस्तै WM-2026-000123",
  "e.g. Kathmandu, Baneshwor...": "जस्तै काठमाडौँ, बानेश्वर...",
  "Enter description...": "विवरण लेख्नुहोस्...",
  "Change Image": "तस्बिर बदल्नुहोस्",
  Image: "तस्बिर",
  "Change Audio": "अडियो बदल्नुहोस्",
  Audio: "अडियो",
  "Audio Unavailable": "अडियो उपलब्ध छैन",
  "Change Video": "भिडियो बदल्नुहोस्",
  Video: "भिडियो",
  "Picker Error": "पिकर त्रुटि",
  "Could not pick image": "तस्बिर छान्न सकिएन",
  "Could not record audio": "अडियो रेकर्ड गर्न सकिएन",
  "Could not capture video": "भिडियो खिच्न सकिएन",
  "Could not capture image": "तस्बिर खिच्न सकिएन",
  "Audio Recording Permission": "अडियो रेकर्डिङ अनुमति",
  "Allow microphone access to record audio for this report.": "यो रिपोर्टका लागि अडियो रेकर्ड गर्न माइक्रोफोन पहुँच दिनुहोस्।",
  "Microphone access needed": "माइक्रोफोन पहुँच आवश्यक छ",
  "Please allow microphone access to record audio for this report.": "यो रिपोर्टका लागि अडियो रेकर्ड गर्न कृपया माइक्रोफोन पहुँच अनुमति दिनुहोस्।",
  "Ask Me Later": "पछि सोध्नुहोस्",
  "Could not pick audio": "अडियो छान्न सकिएन",
  "Could not pick video": "भिडियो छान्न सकिएन",
  "Audio upload": "अडियो अपलोड",
  "Rebuild the app once to enable audio attachments.": "अडियो संलग्न फाइल सक्षम गर्न एप फेरि बनाउनुहोस्।",
  "Selected image": "छानिएको तस्बिर",
  "Selected audio": "छानिएको अडियो",
  "Selected video": "छानिएको भिडियो",
  "Police Alert": "प्रहरी अलर्ट",
  Call: "कल",
  Tracking: "ट्र्याकिङ",
  Ambulance: "एम्बुलेन्स",
  "Fire Service": "दमकल सेवा",
  "Traffic Control": "ट्राफिक नियन्त्रण",
  "Child Helpline": "बाल हेल्पलाइन",
  "Suicide Prevention": "आत्महत्या रोकथाम",
  "Women and GBV Support": "महिला तथा लैङ्गिक हिंसा सहायता",
  "Emergency Contact": "आपतकालीन सम्पर्क",
  "Add a personal emergency contact in Settings first.": "पहिले सेटिङमा व्यक्तिगत आपतकालीन सम्पर्क थप्नुहोस्।",
  "User Email": "प्रयोगकर्ताको इमेल",
  Reason: "कारण",
  Amount: "रकम",
  "Fine Code (optional)": "जरिवाना कोड (ऐच्छिक)",
  "Leave blank to auto-generate": "स्वतः बनाउन खाली छोड्नुहोस्",
  "Over Speeding": "ओभर स्पिडिङ",
  "Payment Return": "भुक्तानी फिर्ता",
  "Payment Canceled": "भुक्तानी रद्द भयो",
  "Start payment first": "पहिले भुक्तानी सुरु गर्नुहोस्",
  "No payable fine found for your account": "तपाईंको खातामा तिर्नुपर्ने जरिवाना भेटिएन",
  "Failed to load your fines": "तपाईंका जरिवानाहरू लोड गर्न असफल",
  "Failed to initiate payment": "भुक्तानी सुरु गर्न असफल",
  "Verification failed": "प्रमाणीकरण असफल",
  "Something went wrong": "केही गलत भयो",
  "Open Reports": "खुला रिपोर्टहरू",
  Counsellors: "परामर्शदाता",
  Therapists: "थेरापिस्टहरू",
  "Total Staff": "कुल कर्मचारी",
  "Create Staff": "कर्मचारी सिर्जना गर्नुहोस्",
  "Create Staff Account": "कर्मचारी खाता सिर्जना गर्नुहोस्",
  "Staff List": "कर्मचारी सूची",
  "Manage Users": "प्रयोगकर्ता व्यवस्थापन",
  "Manage Reports": "रिपोर्ट व्यवस्थापन",
  "Review Donations": "दान समीक्षा",
  "Waste Reports": "फोहोर रिपोर्टहरू",
  "Add counsellor / therapist / police / municipality": "परामर्शदाता / थेरापिस्ट / प्रहरी / नगरपालिका थप्नुहोस्",
  "View, disable, and monitor accounts": "खाताहरू हेर्नुहोस्, निष्क्रिय गर्नुहोस्, र निगरानी गर्नुहोस्",
  "All reports (assign, status, priority)": "सबै रिपोर्टहरू (जिम्मेवारी, स्थिति, प्राथमिकता)",
  "Approve or reject charity requests": "दान अनुरोध स्वीकृत वा अस्वीकृत गर्नुहोस्",
  "Only waste management cases (assign municipality)": "फोहोर व्यवस्थापन सम्बन्धी केसहरू मात्र (नगरपालिका जिम्मा)",
  "Approved requests": "स्वीकृत अनुरोधहरू",
  "Approved charity requests will appear here once admins verify them.": "प्रशासकले प्रमाणित गरेपछि स्वीकृत दान अनुरोध यहाँ देखिनेछन्।",
  "Contact Info": "सम्पर्क जानकारी",
  Location: "स्थान",
  "Type of Help Needed": "आवश्यक सहयोगको प्रकार",
  "Amount Needed": "आवश्यक रकम",
  "Pick Proof Image": "प्रमाण तस्बिर छान्नुहोस्",
  "Submit Request": "अनुरोध पेश गर्नुहोस्",
  "Donate Now": "अहिले दान गर्नुहोस्",
  "Book Session.": "सेसन बुक गर्नुहोस्।",
  "Book Appointment.": "अपोइन्टमेन्ट बुक गर्नुहोस्।",
  "Select Counsellor": "परामर्शदाता छान्नुहोस्",
  "Select Therapist": "थेरापिस्ट छान्नुहोस्",
  "No counsellors found. Ask admin to create counsellor accounts.": "कुनै परामर्शदाता भेटिएन। प्रशासकलाई परामर्शदाता खाता सिर्जना गर्न अनुरोध गर्नुहोस्।",
  "No therapists found. Ask admin to create therapist accounts.": "कुनै थेरापिस्ट भेटिएन। प्रशासकलाई थेरापिस्ट खाता सिर्जना गर्न अनुरोध गर्नुहोस्।",
  "Pick therapist": "थेरापिस्ट छान्नुहोस्",
  "Please select a therapist first.": "कृपया पहिले थेरापिस्ट छान्नुहोस्।",
  "Pick counsellor": "परामर्शदाता छान्नुहोस्",
  Time: "समय",
  "Time Slot": "समय अवधि",
  "Time Slot...": "समय अवधि...",
  Year: "वर्ष",
  "Booking…": "बुक हुँदै...",
  "Pick a day": "दिन छान्नुहोस्",
  "Loading counsellors...": "परामर्शदाताहरू लोड हुँदै...",
  "Loading therapists...": "थेरापिस्टहरू लोड हुँदै...",
  "Session Booked ✅": "सेसन बुक भयो ✅",
  "Appointment Booked ✅": "अपोइन्टमेन्ट बुक भयो ✅",
  "Counseling requestId was not received. Please submit the counseling form again.": "परामर्श अनुरोध आईडी प्राप्त भएन। कृपया फारम फेरि पेश गर्नुहोस्।",
  "Therapy requestId was not received. Please submit the therapy form again.": "थेरापी अनुरोध आईडी प्राप्त भएन। कृपया थेरापी फारम फेरि पेश गर्नुहोस्।",
  "No requestId found. Please submit the counseling form again.": "अनुरोध आईडी भेटिएन। कृपया परामर्श फारम फेरि पेश गर्नुहोस्।",
  "No requestId found. Please submit the therapy form again.": "अनुरोध आईडी भेटिएन। कृपया थेरापी फारम फेरि पेश गर्नुहोस्।",
  "This slot is already booked. Please choose another time.": "यो समय पहिले नै बुक भइसकेको छ। कृपया अर्को समय छान्नुहोस्।",
  "Slot not available": "समय उपलब्ध छैन",
  "This time slot is already booked.": "यो समय पहिले नै बुक भइसकेको छ।",
  "Failed to book counseling session": "परामर्श सेसन बुक गर्न असफल",
  "Could not book appointment": "अपोइन्टमेन्ट बुक गर्न सकिएन",
  "Could not load therapists": "थेरापिस्टहरू लोड गर्न सकिएन",
  "Form now keeps booked sessions visible without burying the form.": "फारम लुकाइने बिना अब बुक गरिएका सेसनहरू देखिनेछन्।",
  "Open Counseling, complete the short intake form, then continue to the counsellor list or your booked sessions.": "परामर्श खोल्नुहोस्, छोटो प्रारम्भिक फारम पूरा गर्नुहोस्, अनि परामर्शदाता सूची वा तपाईंका बुक गरिएका सेसनतर्फ जानुहोस्।",
  "Open Therapy to continue with booking, appointments, or your therapist chat.": "बुकिङ, अपोइन्टमेन्ट वा थेरापिस्ट च्याटका लागि थेरापी खोल्नुहोस्।",
  "How do I report an issue?": "म समस्या कसरी रिपोर्ट गर्ने?",
  "How do I donate?": "म कसरी दान गर्ने?",
  "How do I contact a counsellor?": "म परामर्शदातासँग कसरी सम्पर्क गर्ने?",
  "How do I reach NGO support?": "म एनजिओ सहयोगसम्म कसरी पुग्ने?",
  "Hi, ask me about reports, donations, counseling, therapy, traffic, NGO support, or helpline numbers.": "नमस्ते, रिपोर्ट, दान, परामर्श, थेरापी, ट्राफिक, एनजिओ सहयोग वा हेल्पलाइन नम्बरबारे मलाई सोध्न सक्नुहुन्छ।",
  "I could not generate a reply right now. Please try again.": "अहिले जवाफ तयार गर्न सकिनँ। कृपया फेरि प्रयास गर्नुहोस्।",
  "Help chat is unavailable right now. Please try again.": "सहायता च्याट अहिले उपलब्ध छैन। कृपया फेरि प्रयास गर्नुहोस्।",
  "Open Reporting and choose the report type that fits your issue. Use Crime Reporting for police cases, Traffic for road incidents, and Waste or Municipality for local issues.": "रिपोर्टिङ खोल्नुहोस् र तपाईंको समस्यासँग मिल्ने प्रकार छान्नुहोस्। प्रहरीसम्बन्धी केसका लागि अपराध रिपोर्टिङ, सडक घटनाका लागि ट्राफिक, र स्थानीय समस्याका लागि फोहोर वा नगरपालिका प्रयोग गर्नुहोस्।",
  "Open Support for one-tap helplines like Police 100, Fire 101, Ambulance 102, Traffic 103, Child Helpline 1098, Suicide Prevention 1166, and Women and GBV Support 1145. For organization contacts, open the NGO directory.": "प्रहरी १००, दमकल १०१, एम्बुलेन्स १०२, ट्राफिक १०३, बाल हेल्पलाइन १०९८, आत्महत्या रोकथाम ११६६, र महिला तथा लैङ्गिक हिंसा सहायता ११४५ जस्ता एक-ट्याप हेल्पलाइनका लागि सहायता खोल्नुहोस्। संस्थागत सम्पर्कका लागि एनजिओ निर्देशिका खोल्नुहोस्।",
  "I can help with reporting, donations, counseling, therapy, traffic fines, emergency contacts, and NGO support. Try asking how to report an issue, contact a counsellor, reach an NGO, or pay a fine.": "म रिपोर्टिङ, दान, परामर्श, थेरापी, ट्राफिक जरिवाना, आपतकालीन सम्पर्क, र एनजिओ सहयोगमा मद्दत गर्न सक्छु। समस्या कसरी रिपोर्ट गर्ने, परामर्शदातासँग कसरी सम्पर्क गर्ने, एनजिओसम्म कसरी पुग्ने, वा जरिवाना कसरी तिर्ने भनेर सोधेर हेर्नुहोस्।",
  "Support Directory": "सहायता निर्देशिका",
  "Critical help lines should be calm, clear, and one tap away.": "महत्वपूर्ण सहायता नम्बरहरू शान्त, स्पष्ट र एक ट्यापमै उपलब्ध हुनुपर्छ।",
  "Use this directory for immediate services, crisis support, and practical next steps in Nepal.": "नेपालमा तत्काल सेवा, संकट सहयोग, र व्यवहारिक अर्को चरणका लागि यो निर्देशिका प्रयोग गर्नुहोस्।",
  "Emergency Numbers": "आपतकालीन नम्बरहरू",
  "Mental Health & Safety": "मानसिक स्वास्थ्य र सुरक्षा",
  "What To Do First": "पहिले के गर्ने",
  "Immediate danger, crime, or urgent safety threats.": "तत्काल खतरा, अपराध, वा अत्यावश्यक सुरक्षा जोखिम।",
  "Fire, smoke, explosions, or fast evacuation support.": "आगो, धुँवा, विस्फोट, वा छिटो उद्धार सहायता।",
  "Medical emergencies and serious injury response.": "चिकित्सकीय आपतकालीन अवस्था र गम्भीर चोटपटक सहायता।",
  "Accidents, unsafe roads, or urgent traffic issues.": "दुर्घटना, असुरक्षित सडक, वा अत्यावश्यक ट्राफिक समस्या।",
  "Support for children at risk or in distress.": "जोखिम वा सङ्कटमा रहेका बालबालिकाका लागि सहयोग।",
  "Suicide Prevention Helpline": "आत्महत्या रोकथाम हेल्पलाइन",
  "24/7 confidential emotional crisis support.": "२४/७ गोप्य भावनात्मक संकट सहायता।",
  "Women & GBV Support": "महिला तथा लैङ्गिक हिंसा सहायता",
  "Violence, abuse, and safety guidance from the National Women Commission.": "राष्ट्रिय महिला आयोगबाट हिंसा, दुव्र्यवहार, र सुरक्षा मार्गदर्शन।",
  "If the situation is immediate": "यदि अवस्था तत्काल छ भने",
  "Call police or ambulance first before filling any report flow in the app.": "एपमा कुनै रिपोर्ट फारम भर्नुभन्दा पहिले प्रहरी वा एम्बुलेन्समा सम्पर्क गर्नुहोस्।",
  "If the danger is emotional or personal": "यदि खतरा भावनात्मक वा व्यक्तिगत छ भने",
  "Use the crisis and women's support lines to talk to a real person quickly.": "संकट तथा महिला सहायता लाइन प्रयोग गरेर छिटो वास्तविक व्यक्तिसँग कुरा गर्नुहोस्।",
  "If you need evidence or follow-up": "यदि तपाईंलाई प्रमाण वा पछ्याइ आवश्यक छ भने",
  "Use the app's reporting flows after you are safe so the issue can be documented properly.": "तपाईं सुरक्षित भएपछि एपको रिपोर्टिङ प्रक्रिया प्रयोग गर्नुहोस् ताकि विषय ठीकसँग अभिलेखीकरण होस्।",
  "Unable to open dialer on this device.": "यो डिभाइसमा डायलर खोल्न सकिएन।",
  "Counsellor Workspace": "परामर्शदाता कार्यक्षेत्र",
  "Your day should feel focused, calm, and easy to act on.": "तपाईंको दिन केन्द्रित, शान्त र सहज कार्ययोग्य हुनुपर्छ।",
  "Open Appointments": "अपोइन्टमेन्टहरू खोल्नुहोस्",
  Insights: "अन्तर्दृष्टि",
  "Approve pending sessions, keep confirmed sessions moving, and close completed work cleanly.": "पेन्डिङ सेसन स्वीकृत गर्नुहोस्, पुष्टि भएका सेसनहरू अगाडि बढाउनुहोस्, र सम्पन्न काम सफासँग बन्द गर्नुहोस्।",
  "Open each client once, see their latest context, and jump into chat only when it is available.": "हरेक सेवाग्राही खोल्नुहोस्, तिनीहरूको नयाँ सन्दर्भ हेर्नुहोस्, र उपलब्ध हुँदा मात्र च्याटमा जानुहोस्।",
  "Review session mix, common concerns, and current workload without digging through raw lists.": "कच्चा सूची नखोतली सेसन मिश्रण, सामान्य समस्या, र हालको कामको भार समीक्षा गर्नुहोस्।",
  Open: "खोल्नुहोस्",
  "Recent activity": "हालैको गतिविधि",
  "Latest session updates": "सेसनका पछिल्ला अपडेटहरू",
  Client: "सेवाग्राही",
  Upcoming: "आगामी",
  "No appointment activity yet.": "अहिलेसम्म कुनै अपोइन्टमेन्ट गतिविधि छैन।",
  "Loading appointments...": "अपोइन्टमेन्टहरू लोड हुँदै...",
  "No appointments match this view": "यो दृश्यसँग मेल खाने अपोइन्टमेन्ट छैनन्",
  "Try a different filter or clear the search input.": "अर्को फिल्टर प्रयोग गर्नुहोस् वा खोज इनपुट खाली गर्नुहोस्।",
  "No more actions needed": "थप कार्य आवश्यक छैन",
  "Date pending": "मिति पेन्डिङ",
  "Traffic Rules": "ट्राफिक नियमहरू",
  Rule: "नियम",
  "Keep road guidance tighter, calmer, and easier to scan.": "सडकसम्बन्धी निर्देशन अझ छोटो, शान्त र सजिलै पढ्न मिल्ने बनाउनुहोस्।",
  "The rules are now presented as short cards so users can understand key safety guidance faster.": "अब नियमहरू छोटा कार्डको रूपमा प्रस्तुत गरिएका छन् ताकि प्रयोगकर्ताले मुख्य सुरक्षा निर्देशन छिटो बुझ्न सकून्।",
  "Always carry a valid driving licence.": "सधैं मान्य सवारी अनुमति पत्र बोक्नुहोस्।",
  "Drivers must carry a valid licence and registration documents on public roads.": "सार्वजनिक सडकमा चालकले मान्य लाइसेन्स र दर्ता कागजात साथमा राख्नुपर्छ।",
  "Wear seat belt and helmet.": "सिट बेल्ट र हेलमेट लगाउनुहोस्।",
  "Car occupants should use seat belts and two-wheeler riders must wear certified helmets.": "कारमा सवार व्यक्तिले सिट बेल्ट प्रयोग गर्नुपर्छ र दुईपांग्रे सवारी चालकले प्रमाणित हेलमेट लगाउनुपर्छ।",
  "Do not drive under alcohol or drugs.": "मादक पदार्थ वा लागूपदार्थ सेवन गरेर सवारी नचलाउनुहोस्।",
  "Anything that reduces judgement or focus makes driving unsafe and illegal.": "निर्णय क्षमता वा ध्यान घटाउने कुनै पनि कुरा सवारी चलाउन असुरक्षित र गैरकानुनी बनाउँछ।",
  "Follow lane discipline and speed limits.": "लेन अनुशासन र गति सीमा पालना गर्नुहोस्।",
  "Stay in marked lanes and obey speed limits set by traffic police and local authority.": "चिन्हित लेनमै रहनुहोस् र ट्राफिक प्रहरी तथा स्थानीय निकायले तोकेको गति सीमा पालना गर्नुहोस्।",
  "Give priority to pedestrians.": "पैदलयात्रीलाई प्राथमिकता दिनुहोस्।",
  "Slow near crossings, schools, and hospitals and allow safe pedestrian movement.": "क्रसिङ, विद्यालय र अस्पताल नजिक गति घटाउनुहोस् र पैदलयात्रीलाई सुरक्षित रूपमा हिँड्न दिनुहोस्।",
  "View My Reports": "मेरा रिपोर्टहरू हेर्नुहोस्",
  Official: "आधिकारिक",
  "Tip: You can track status later from “My Reports” using your Report Code.": "सुझाव: तपाईंले पछि आफ्नो रिपोर्ट कोड प्रयोग गरेर “मेरा रिपोर्टहरू” बाट स्थिति ट्र्याक गर्न सक्नुहुन्छ।",
  "Staff profile fields are available below.": "कर्मचारी प्रोफाइलका फिल्डहरू तल उपलब्ध छन्।",
  "Users can edit their basic details here.": "प्रयोगकर्ताले यहाँ आफ्नो आधारभूत विवरण सम्पादन गर्न सक्छन्।",
  "Loading...": "लोड हुँदै...",
  "result(s)": " परिणाम",
  January: "जनवरी",
  February: "फेब्रुअरी",
  March: "मार्च",
  April: "अप्रिल",
  May: "मे",
  June: "जुन",
  July: "जुलाई",
  August: "अगस्ट",
  September: "सेप्टेम्बर",
  October: "अक्टोबर",
  November: "नोभेम्बर",
  December: "डिसेम्बर",
  Mo: "सो",
  Tu: "मं",
  We: "बु",
  Th: "बि",
  Fr: "शु",
  Sa: "श",
  Su: "आ",
};

function normalizeTranslationKey(value) {
  return String(value || "")
    .replace(/\u2026/g, "...")
    .replace(/[’]/g, "'")
    .replace(/\s+/g, " ")
    .trim();
}

export function translateText(value, language = "English") {
  const normalizedLanguage = normalizeAppLanguage(language);

  if (normalizedLanguage !== "Nepali" || typeof value !== "string") {
    return value;
  }

  const normalized = normalizeTranslationKey(value);
  if (!normalized) {
    return value;
  }

  return EXACT_TRANSLATIONS[normalized] || value;
}

export function getLocalizedCopy(copyByLanguage, language) {
  const normalizedLanguage = normalizeAppLanguage(language);
  return copyByLanguage[normalizedLanguage] || copyByLanguage.English;
}

export function useResolvedAppLanguage() {
  const { language } = useAppTheme();
  const normalizedContextLanguage = normalizeAppLanguage(language);
  const [resolvedLanguage, setResolvedLanguage] = useState(normalizedContextLanguage);

  useEffect(() => {
    setResolvedLanguage(normalizedContextLanguage);
  }, [normalizedContextLanguage]);

  const refreshLanguage = useCallback(async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
      if (savedLanguage) {
        setResolvedLanguage(normalizeAppLanguage(savedLanguage));
        return;
      }
    } catch {
      // Fall back to the in-memory language if storage cannot be read.
    }

    setResolvedLanguage(normalizedContextLanguage);
  }, [normalizedContextLanguage]);

  useEffect(() => {
    refreshLanguage();
  }, [refreshLanguage]);

  return {
    language: resolvedLanguage,
    refreshLanguage,
  };
}

export function useTranslate() {
  const { language } = useResolvedAppLanguage();
  return useMemo(() => (value) => translateText(value, language), [language]);
}

export function useLocalizedCopy(copyByLanguage) {
  const { language } = useResolvedAppLanguage();
  return useMemo(() => getLocalizedCopy(copyByLanguage, language), [copyByLanguage, language]);
}

export function getLanguageLabel(option, uiLanguage = "English") {
  const normalizedUiLanguage = normalizeAppLanguage(uiLanguage);
  const normalizedOption = normalizeAppLanguage(option);
  return LANGUAGE_OPTION_LABELS[normalizedUiLanguage]?.[normalizedOption] || option;
}

export function getRoleLabel(role, uiLanguage = "English") {
  const safeRole = String(role || "user").toLowerCase();
  return ROLE_LABELS[safeRole]?.[uiLanguage] || role || ROLE_LABELS.user[uiLanguage];
}
